[colors.bright]
black = "0x839496"
blue = "0x839496"
cyan = "0x93a1a1"
green = "0x586e75"
magenta = "0x6c71c4"
red = "0xcb4b16"
white = "0xfdf6e3"
yellow = "0x657b83"

[colors.normal]
black = "0x073642"
blue = "0x268bd2"
cyan = "0x2aa198"
green = "0x859900"
magenta = "0xd33682"
red = "0xdc322f"
white = "0xeee8d5"
yellow = "0xb58900"

[colors.primary]
background = "0x002b36"
foreground = "0x839496"

[env]
TERM = "xterm-256color"

[font]
size = 14.5

[font.bold]
family = "JetBrains Mono"
style = "Bold"

[font.bold_italic]
family = "JetBrains Mono"
style = "Bold Italic"

[font.italic]
family = "JetBrains Mono"
style = "Italic"

[font.normal]
family = "JetBrains Mono"
style = "ExtraLight"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Command|Shift"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Command|Shift"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "N"
mods = "Control"

[[keyboard.bindings]]
chars = "\u0001"
key = "A"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002"
key = "B"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0003"
key = "C"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0004"
key = "D"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0005"
key = "E"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0006"
key = "F"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0007"
key = "G"
mods = "Command"

[[keyboard.bindings]]
chars = "\b"
key = "H"
mods = "Command"

[[keyboard.bindings]]
chars = "\t"
key = "I"
mods = "Command"

[[keyboard.bindings]]
chars = """

"""
key = "J"
mods = "Command"

[[keyboard.bindings]]
chars = "\u000B"
key = "K"
mods = "Command"

[[keyboard.bindings]]
chars = "\f"
key = "L"
mods = "Command"

[[keyboard.bindings]]
chars = "\r"
key = "M"
mods = "Command"

[[keyboard.bindings]]
chars = "\u000E"
key = "N"
mods = "Command"

[[keyboard.bindings]]
chars = "\u000F"
key = "O"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0010"
key = "P"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0011"
key = "Q"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0012"
key = "R"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0013"
key = "S"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0014"
key = "T"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0015"
key = "U"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0016"
key = "V"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0017"
key = "W"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0018"
key = "X"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0019"
key = "Y"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001A"
key = "Z"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001B"
key = "LBracket"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001C"
key = "Backslash"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001D"
key = "RBracket"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001E"
key = "Key6"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001F"
key = "Minus"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001Ba"
key = "A"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bb"
key = "B"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bc"
key = "C"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bd"
key = "D"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Be"
key = "E"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bf"
key = "F"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bg"
key = "G"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bh"
key = "H"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bi"
key = "I"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bj"
key = "J"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bk"
key = "K"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bl"
key = "L"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bm"
key = "M"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bn"
key = "N"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bo"
key = "O"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bp"
key = "P"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bq"
key = "Q"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Br"
key = "R"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bs"
key = "S"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bt"
key = "T"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bu"
key = "U"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bv"
key = "V"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bw"
key = "W"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bx"
key = "X"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001By"
key = "Y"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bz"
key = "Z"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B1"
key = "Key1"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B2"
key = "Key2"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B3"
key = "Key3"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B4"
key = "Key4"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B5"
key = "Key5"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B6"
key = "Key6"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B7"
key = "Key7"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B8"
key = "Key8"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B9"
key = "Key9"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B0"
key = "Key0"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B\u0001"
key = "A"
mods = "Command|Alt"

[[keyboard.bindings]]
chars = "\u001B\u0002"
key = "B"
mods = "Command|Alt"

[[keyboard.bindings]]
chars = "\u001B\u0003"
key = "C"
mods = "Command|Alt"

[[keyboard.bindings]]
chars = "\u001B\u0004"
key = "D"
mods = "Command|Alt"

[[keyboard.bindings]]
chars = "\u001B\u0005"
key = "E"
mods = "Command|Alt"

[[keyboard.bindings]]
chars = "\u001B\u0006"
key = "F"
mods = "Command|Alt"

[[keyboard.bindings]]
chars = "\u001B\u0007"
key = "G"
mods = "Command|Alt"

[[keyboard.bindings]]
chars = "\u001B\b"
key = "H"
mods = "Command|Alt"

[[keyboard.bindings]]
chars = "\u001B\t"
key = "I"
mods = "Command|Alt"

[[keyboard.bindings]]
chars = """
\u001B
"""
key = "J"
mods = "Command|Alt"

[[keyboard.bindings]]
chars = "\u001B\u000B"
key = "K"
mods = "Command|Alt"

[[keyboard.bindings]]
chars = "\u001B\f"
key = "L"
mods = "Command|Alt"

[[keyboard.bindings]]
chars = "\u001B\r"
key = "M"
mods = "Command|Alt"

[[keyboard.bindings]]
chars = "\u001B\u000E"
key = "N"
mods = "Command|Alt"

[[keyboard.bindings]]
chars = "\u001B\u000F"
key = "O"
mods = "Command|Alt"

[[keyboard.bindings]]
chars = "\u001B\u0010"
key = "P"
mods = "Command|Alt"

[[keyboard.bindings]]
chars = "\u001B\u0011"
key = "Q"
mods = "Command|Alt"

[[keyboard.bindings]]
chars = "\u001B\u0012"
key = "R"
mods = "Command|Alt"

[[keyboard.bindings]]
chars = "\u001B\u0013"
key = "S"
mods = "Command|Alt"

[[keyboard.bindings]]
chars = "\u001B\u0014"
key = "T"
mods = "Command|Alt"

[[keyboard.bindings]]
chars = "\u001B\u0015"
key = "U"
mods = "Command|Alt"

[[keyboard.bindings]]
chars = "\u001B\u0016"
key = "V"
mods = "Command|Alt"

[[keyboard.bindings]]
chars = "\u001B\u0017"
key = "W"
mods = "Command|Alt"

[[keyboard.bindings]]
chars = "\u001B\u0018"
key = "X"
mods = "Command|Alt"

[[keyboard.bindings]]
chars = "\u001B\u0019"
key = "Y"
mods = "Command|Alt"

[[keyboard.bindings]]
chars = "\u001B\u001A"
key = "Z"
mods = "Command|Alt"

[[keyboard.bindings]]
chars = "\u001B\b"
key = "H"
mods = "Command|Alt"

[[keyboard.bindings]]
chars = "\u001B\f"
key = "L"
mods = "Command|Alt"

[[keyboard.bindings]]
chars = """
\u001B
"""
key = "J"
mods = "Command|Alt"

[[keyboard.bindings]]
chars = "\u001B\u000B"
key = "K"
mods = "Command|Alt"

[[keyboard.bindings]]
chars = "\u001BA"
key = "A"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001BB"
key = "B"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001BC"
key = "C"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001BD"
key = "D"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001BE"
key = "E"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001BF"
key = "F"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001BG"
key = "G"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001BH"
key = "H"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001BI"
key = "I"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001BJ"
key = "J"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001BK"
key = "K"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001BL"
key = "L"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001BM"
key = "M"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001BN"
key = "N"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001BO"
key = "O"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001BP"
key = "P"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001BQ"
key = "Q"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001BR"
key = "R"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001BS"
key = "S"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001BT"
key = "T"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001BU"
key = "U"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001BV"
key = "V"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001BW"
key = "W"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001BX"
key = "X"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001BY"
key = "Y"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001BZ"
key = "Z"
mods = "Alt|Shift"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "-"
mods = "Command"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "="
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "="
mods = "Command"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "-"
mods = "Control"
