#! /bin/zsh

# install vimplug

sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs \
       https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'

for folder in */ ;
do
  stow -D "$folder"
  echo "stow $folder"
  stow "$folder"
done

