" Generated by vim-plug
" Thu May 18 03:57:59 2023
" :source this file in vim to restore the snapshot
" or execute: vim -S snapshot.vim

silent! let g:plugs['Comment.nvim'].commit = 'e1fe53117aab24c378d5e6deaad786789c360123'
silent! let g:plugs['LuaSnip'].commit = 'b4bc24c4925aeb05fd47d2ee9b24b7f73f5d7e32'
silent! let g:plugs['cmp-buffer'].commit = '3022dbc9166796b644a841a02de8dd1cc1d311fa'
silent! let g:plugs['cmp-nvim-lsp'].commit = '0e6b2ed705ddcff9738ec4ea838141654f12eeef'
silent! let g:plugs['cmp_luasnip'].commit = '18095520391186d634a0045dacaa346291096566'
silent! let g:plugs['impatient.nvim'].commit = '47302af74be7b79f002773011f0d8e85679a7618'
silent! let g:plugs['indent-blankline.nvim'].commit = '018bd04d80c9a73d399c1061fa0c3b14a7614399'
silent! let g:plugs['leap.nvim'].commit = '3144cefc5ec8872c838dc6710707d23b6de5ec02'
silent! let g:plugs['lualine.nvim'].commit = '05d78e9fd0cdfb4545974a5aa14b1be95a86e9c9'
silent! let g:plugs['moonbow.nvim'].commit = '2564c8a8efc18eb65104c75b404972e4fabd1d25'
silent! let g:plugs['nvim-cmp'].commit = '3ac8d6cd29c74ff482d8ea47d45e5081bfc3f5ad'
silent! let g:plugs['nvim-lsp-installer'].commit = '17e0bfa5f2c8854d1636fcd036dc8284db136baa'
silent! let g:plugs['nvim-lspconfig'].commit = '8dc45a5c142f0b5a5dd34e5cdba33217d5dc6a86'
silent! let g:plugs['nvim-treesitter'].commit = '102f1b2f55575f0a2f18be92eafc0e7142024ad1'
silent! let g:plugs['playground'].commit = '2b81a018a49f8e476341dfcb228b7b808baba68b'
silent! let g:plugs['plenary.nvim'].commit = '9ac3e9541bbabd9d73663d757e4fe48a675bb054'
silent! let g:plugs['shade.nvim'].commit = '4286b5abc47d62d0c9ffb22a4f388b7bf2ac2461'
silent! let g:plugs['tagbar'].commit = 'be563539754b7af22bbe842ef217d4463f73468c'
silent! let g:plugs['telescope.nvim'].commit = '40c31fdde93bcd85aeb3447bb3e2a3208395a868'
silent! let g:plugs['tokyonight.nvim'].commit = 'df13e3268a44f142999fa166572fe95a650a0b37'
silent! let g:plugs['vim-tmux-navigator'].commit = 'cdd66d6a37d991bba7997d593586fc51a5b37aa8'
silent! let g:plugs['vscode.nvim'].commit = 'dc5f37603ada51db13bc4009cbee628c5857a274'

PlugUpdate!

