require("impatient").enable_profile()
require("renny.lualine")
require("renny.comment")
require("renny.telescope")
require("renny.indent_blankline")
require("renny.luasnip")
require("renny.completion")
require("renny.ts")
require("renny.lsp")
require("renny.leap")
-- require("cscope_maps").setup({})
